# Generated by Django 5.0.6 on 2026-06-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='audit_note',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='variable',
            name='last_audit_at',
            field=models.DateTimeField(blank=True, help_text='Last time a scan checked this key', null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Last time a scan found this key referenced in code', null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='suspected_unused',
            field=models.BooleanField(default=False),
        ),
    ]
