# Generated by Django 5.0.6 on 2026-06-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0002_variable_audit_note_variable_last_audit_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='variable',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variable',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='archived_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='variable',
            name='archived_reason',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddConstraint(
            model_name='variable',
            constraint=models.UniqueConstraint(condition=models.Q(('archived', False)), fields=('environment', 'key'), name='uniq_active_env_key'),
        ),
    ]
