# Generated by Django 5.0.6 on 2026-06-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0003_alter_variable_unique_together_variable_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='bitbucket_uuid',
        ),
        migrations.DeleteModel(
            name='ApiToken',
        ),
    ]
