# Generated by Django 5.0.6 on 2026-06-18 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0004_remove_appuser_bitbucket_uuid_delete_apitoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['group', 'key']},
        ),
        migrations.RemoveConstraint(
            model_name='variable',
            name='uniq_active_env_key',
        ),
        migrations.AddField(
            model_name='variable',
            name='group',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='variable',
            name='target',
            field=models.ForeignKey(blank=True, help_text='Blank = applies to all targets; set = overrides the base for that target only', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='vars.target'),
        ),
        migrations.AddConstraint(
            model_name='variable',
            constraint=models.UniqueConstraint(condition=models.Q(('archived', False), ('target__isnull', True)), fields=('environment', 'key'), name='uniq_active_env_key_alltargets'),
        ),
        migrations.AddConstraint(
            model_name='variable',
            constraint=models.UniqueConstraint(condition=models.Q(('archived', False), ('target__isnull', False)), fields=('environment', 'target', 'key'), name='uniq_active_env_target_key'),
        ),
    ]
