# Generated by Django 5.0.6 on 2026-06-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0005_alter_variable_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['label', 'key']},
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='group',
            new_name='label',
        ),
    ]
