# Generated by Django 5.0.6 on 2026-06-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0006_alter_variable_options_rename_group_variable_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='archived_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
