# Generated by Django 5.0.6 on 2026-06-19 00:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0007_environment_archived_environment_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_label', models.CharField(blank=True, max_length=120)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('on_box_only', models.JSONField(default=list)),
                ('in_keymaker_only', models.JSONField(default=list)),
                ('value_mismatch', models.JSONField(default=list)),
                ('in_sync', models.BooleanField(default=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_checks', to='vars.environment')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['environment', 'target_label', '-checked_at'], name='vars_driftc_environ_d4826c_idx')],
            },
        ),
    ]
