# Generated by Django 5.0.6 on 2026-07-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0008_driftcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftcheck',
            name='dokku_managed',
            field=models.JSONField(default=list),
        ),
    ]
