# Generated by Django 5.0.6 on 2026-08-13 15:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0009_driftcheck_dokku_managed'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('target_label', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=400)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_keys', to='vars.environment')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddConstraint(
            model_name='ignoredkey',
            constraint=models.UniqueConstraint(fields=('environment', 'key', 'target_label'), name='uniq_ignored_key_scope'),
        ),
    ]
